using System;
using System.IO;
using System.Drawing;
using System.Drawing.Drawing2D;
using System.Windows.Forms;
using System.Diagnostics;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using System.Web.Script.Serialization;

[assembly: System.Reflection.AssemblyTitle("LakeSkin 湖畔换肤")]
[assembly: System.Reflection.AssemblyVersion("1.0.0.0")]
namespace LakeSkin {
public class Theme {
 public int Version {get;set;} public string Name {get;set;} public string Accent {get;set;} public string Background {get;set;} public bool Icons {get;set;}
 public Theme(){Version=1;Name="玫瑰粉";Accent="#CD4880";Background="default";Icons=true;}
 public Theme Clone(){return new Theme{Version=Version,Name=Name,Accent=Accent,Background=Background,Icons=Icons};}
 public void Validate(){if(Version!=1)throw new Exception("不支持这个主题文件版本。");if(String.IsNullOrWhiteSpace(Name)||Name.Length>40)throw new Exception("主题名称需为 1–40 个字符。");ColorValue(Accent);if(Background!="default")ColorValue(Background);}
 public static Color ColorValue(string s){if(s==null||!System.Text.RegularExpressions.Regex.IsMatch(s,"^#[0-9a-fA-F]{6}$"))throw new Exception("颜色格式应为 #RRGGBB，例如 #CD4880。");return ColorTranslator.FromHtml(s);}
}
public static class Storage {
 public static string Root=AppDomain.CurrentDomain.BaseDirectory;
 public static string Engine=Path.Combine(Root,"engine");
 public static JavaScriptSerializer Json=new JavaScriptSerializer();
 public static void Write(string path,string data){Directory.CreateDirectory(Path.GetDirectoryName(path));string tmp=path+".tmp";File.WriteAllText(tmp,data,new System.Text.UTF8Encoding(false));if(File.Exists(path))File.Replace(tmp,path,null);else File.Move(tmp,path);}
 public static Theme Read(string path){if(new FileInfo(path).Length>65536)throw new Exception("主题文件过大。");Theme t=Json.Deserialize<Theme>(File.ReadAllText(path));if(t==null)throw new Exception("主题文件为空。");t.Validate();return t;}
 public static string Qss(Theme t){t.Validate();Color c=Theme.ColorValue(t.Accent);string pale=ColorTranslator.ToHtml(Color.FromArgb((c.R+255*8)/9,(c.G+255*8)/9,(c.B+255*8)/9));string fg=(.2126*c.R+.7152*c.G+.0722*c.B)>160?"#20242c":"#ffffff";return "/* LakeSkin: generated theme */\nQWidget { selection-background-color:"+t.Accent+"; selection-color:"+fg+"; }\nQMenu::item:selected, QAbstractItemView::item:selected {background:"+t.Accent+";color:"+fg+";}\nQPushButton:hover {background:"+pale+";}\n"+(t.Background=="default"?"":"QWidget {background-color:"+t.Background+";color:"+((.2126*Theme.ColorValue(t.Background).R+.7152*Theme.ColorValue(t.Background).G+.0722*Theme.ColorValue(t.Background).B)<128?"#F3F4F6":"#272B34")+";}\n");}
 public static void Prepare(Theme t){t.Validate();Write(Path.Combine(Engine,"theme.qss"),Qss(t));Write(Path.Combine(Engine,"theme.cfg"),t.Accent.Substring(1)+" "+(t.Icons?"1":"0"));Write(Path.Combine(Root,"themes","last-theme.json"),Json.Serialize(t));}
 public static void Log(string message){try{Directory.CreateDirectory(Path.Combine(Root,"data"));File.AppendAllText(Path.Combine(Root,"data","activity.log"),DateTime.Now.ToString("s")+" "+message+Environment.NewLine);}catch{}}
}
public class PaletteButton:Button {
 public Color Swatch {get;set;} public bool Chosen;
 public PaletteButton(string name,Color c){Text=name;Swatch=c;Size=new Size(80,62);FlatStyle=FlatStyle.Flat;FlatAppearance.BorderSize=0;BackColor=Color.White;Cursor=Cursors.Hand;Margin=new Padding(0,0,8,8);}
 protected override void OnPaint(PaintEventArgs e){e.Graphics.SmoothingMode=SmoothingMode.AntiAlias;e.Graphics.Clear(Chosen?Color.FromArgb(242,240,248):Color.White);using(SolidBrush b=new SolidBrush(Swatch))e.Graphics.FillEllipse(b,30,8,20,20);TextRenderer.DrawText(e.Graphics,Text,Font,new Rectangle(0,34,Width,22),Color.FromArgb(48,52,65),TextFormatFlags.HorizontalCenter);if(Chosen)using(Pen p=new Pen(Swatch,2))e.Graphics.DrawRectangle(p,1,1,Width-3,Height-3);}
}
public class Preview:Control {
 public Theme Current=new Theme();public Preview(){DoubleBuffered=true;BackColor=Color.White;Dock=DockStyle.Fill;MinimumSize=new Size(360,290);}
 void Box(Graphics g,Color c,float x,float y,float w,float h){using(SolidBrush b=new SolidBrush(c))g.FillRectangle(b,x,y,w,h);}
 void Txt(Graphics g,string s,float size,Color c,float x,float y,bool bold=false){using(Font f=new Font("Microsoft YaHei UI",size,bold?FontStyle.Bold:FontStyle.Regular))using(SolidBrush b=new SolidBrush(c))g.DrawString(s,f,b,x,y);}
 protected override void OnPaint(PaintEventArgs e){base.OnPaint(e);Graphics g=e.Graphics;g.SmoothingMode=SmoothingMode.AntiAlias;float scale=Math.Min(Width/480f,Height/390f);g.TranslateTransform((Width-480*scale)/2,(Height-390*scale)/2);g.ScaleTransform(scale,scale);Color a=Theme.ColorValue(Current.Accent),ink=Color.FromArgb(44,49,61),muted=Color.FromArgb(129,137,151);Color bg=Current.Background=="default"?Color.FromArgb(245,246,250):Theme.ColorValue(Current.Background);Color pale=Color.FromArgb((a.R+255*7)/8,(a.G+255*7)/8,(a.B+255*7)/8);Box(g,Color.FromArgb(229,234,241),0,0,52,390);Box(g,Color.FromArgb(244,246,249),52,0,142,390);Box(g,bg,194,0,286,390);Box(g,Color.White,194,0,286,47);Txt(g,"湖畔交流",12,ink,210,15,true);
 for(int i=0;i<6;i++){Color ic=Current.Icons?a:Color.FromArgb(55,135,239);using(SolidBrush b=new SolidBrush(i==0?ic:muted))g.FillEllipse(b,17,70+i*45,18,18);}using(SolidBrush b=new SolidBrush(Color.FromArgb(129,157,178)))g.FillEllipse(b,12,17,28,28);Txt(g,"搜索",9,muted,70,17);Box(g,a,59,59,128,62);Color sel=(.2126*a.R+.7152*a.G+.0722*a.B)>160?ink:Color.White;Txt(g,"湖畔交流",10,sel,71,70,true);Txt(g,"今天也要好心情",8,sel,71,93);for(int i=0;i<4;i++){Txt(g,new[]{"课程讨论","校园活动","文件助手","好友消息"}[i],10,ink,70,137+i*48);Txt(g,"新的消息…",8,muted,70,158+i*48);}Txt(g,"10:24",8,muted,308,66);Box(g,Color.White,210,93,212,65);Txt(g,"选一个喜欢的颜色",10,ink,222,105);Txt(g,"让日常界面更合心意。",9,muted,222,129);Box(g,pale,252,180,208,54);Txt(g,"这就是我的配色。",10,ink,268,197);Color person=Current.Icons?a:Color.FromArgb(55,135,239);using(SolidBrush b=new SolidBrush(person))g.FillEllipse(b,212,184,18,18);Box(g,Color.White,194,272,286,118);Txt(g,"＋   ☺   ⋯",13,muted,210,282);Txt(g,"输入消息…",10,muted,210,321);Box(g,a,389,348,69,28);Txt(g,"发送",9,sel,407,354);}
}
public class MainWindow:Form {
 Theme theme=new Theme();Preview preview=new Preview();TextBox accent=new TextBox(),name=new TextBox(),bgHex=new TextBox(),clientPath=new TextBox();ComboBox backgrounds=new ComboBox(),saved=new ComboBox();CheckBox icons=new CheckBox();Label status=new Label(),hint=new Label(),previewLabel=new Label();Button apply,restore;List<PaletteButton> swatches=new List<PaletteButton>();List<string> themeFiles=new List<string>();bool loading=false,busy=false;System.Windows.Forms.Timer timer=new System.Windows.Forms.Timer();
 readonly string[] presetNames={"玫瑰粉","鸢尾紫","湖水蓝","薄荷绿","琥珀金","珊瑚红","石墨灰","午夜蓝"};readonly string[] presetColors={"#CD4880","#8257D6","#2689CF","#26997A","#C58A24","#DD655A","#626977","#354F79"};
 public MainWindow(){Text="湖畔换肤 · LakeSkin";Font=new Font("Microsoft YaHei UI",9F);BackColor=Color.FromArgb(245,246,249);Size=new Size(1140,800);MinimumSize=new Size(1060,760);StartPosition=FormStartPosition.CenterScreen;try{Icon=Icon.ExtractAssociatedIcon(Application.ExecutablePath);}catch{}AutoScaleMode=AutoScaleMode.Dpi;
 try{string last=Path.Combine(Storage.Root,"themes","last-theme.json");if(File.Exists(last))theme=Storage.Read(last);}catch{}
 TableLayoutPanel page=new TableLayoutPanel{Dock=DockStyle.Fill,ColumnCount=1,RowCount=3,Padding=new Padding(28,22,28,18)};page.RowStyles.Add(new RowStyle(SizeType.Absolute,88));page.RowStyles.Add(new RowStyle(SizeType.Percent,100));page.RowStyles.Add(new RowStyle(SizeType.Absolute,72));Controls.Add(page);
 Panel header=new Panel{Dock=DockStyle.Fill};header.Controls.Add(new Label{Text="湖畔换肤",Font=new Font("Microsoft YaHei UI",24,FontStyle.Bold),AutoSize=true,Location=new Point(0,0),ForeColor=Color.FromArgb(34,40,53)});header.Controls.Add(new Label{Text="LAKESKIN  /  为 i西湖挑一份好心情",AutoSize=true,Location=new Point(3,48),ForeColor=Color.FromArgb(126,133,148)});Button help=Btn("使用说明",100);help.Dock=DockStyle.Right;help.Height=34;help.Click+=(s,e)=>MessageBox.Show(this,"1. 打开 i西湖，选择预设或输入自定义色号。\n2. 右侧先预览，点击“应用到 i西湖”后才改变客户端。\n3. 使用“恢复默认”可关闭本次换色；完整退出客户端也会恢复。\n4. 可保存、导入和导出 JSON 主题。\n\n仅适配 Qt 5.15.18 的 i西湖版本。部分第三方 Logo、网页与自绘区域可能不跟随。修改只在本机进程内生效，不更改安装文件和聊天数据。软件不发送消息、不上传图片。\n\n导入文件仅包含颜色和选项，不执行代码。关闭本工具后，已经应用的主题继续保留至客户端退出。","湖畔换肤",MessageBoxButtons.OK,MessageBoxIcon.Information);Panel helpWrap=new Panel{Dock=DockStyle.Right,Width=104,Padding=new Padding(0,10,0,40)};helpWrap.Controls.Add(help);header.Controls.Add(helpWrap);page.Controls.Add(header,0,0);
 TableLayoutPanel body=new TableLayoutPanel{Dock=DockStyle.Fill,ColumnCount=2,RowCount=1};body.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute,414));body.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,100));page.Controls.Add(body,0,1);
 Panel config=new Panel{Dock=DockStyle.Fill,BackColor=Color.White,Padding=new Padding(22),AutoScroll=true,Margin=new Padding(0,0,18,0)};body.Controls.Add(config,0,0);int y=17;
 AddLabel(config,"01  选择主色",15,FontStyle.Bold,y);y+=38;FlowLayoutPanel colors=new FlowLayoutPanel{Location=new Point(22,y),Size=new Size(372,142),Margin=new Padding(0)};config.Controls.Add(colors);for(int i=0;i<presetNames.Length;i++){int index=i;PaletteButton b=new PaletteButton(presetNames[i],Theme.ColorValue(presetColors[i]));b.Click+=(s,e)=>{theme.Accent=presetColors[index];theme.Name=presetNames[index];LoadFields();};colors.Controls.Add(b);swatches.Add(b);}y+=148;
 accent.Location=new Point(22,y);accent.Size=new Size(237,30);accent.Font=new Font("Consolas",12);Button pick=Btn("自定义颜色",113);pick.Location=new Point(272,y-2);pick.Click+=(s,e)=>PickColor(false);config.Controls.Add(accent);config.Controls.Add(pick);accent.TextChanged+=(s,e)=>UpdateTheme();y+=47;
 AddLabel(config,"02  背景与图标",12,FontStyle.Bold,y);y+=33;backgrounds.DropDownStyle=ComboBoxStyle.DropDownList;backgrounds.DrawMode=DrawMode.OwnerDrawFixed;backgrounds.DrawItem+=(s,e)=>{e.DrawBackground();if(e.Index>=0)TextRenderer.DrawText(e.Graphics,backgrounds.Items[e.Index].ToString(),Font,e.Bounds,Color.FromArgb(55,61,76),TextFormatFlags.Left|TextFormatFlags.VerticalCenter);};backgrounds.Items.AddRange(new object[]{"跟随客户端默认背景","纯白背景","自定义背景"});backgrounds.Location=new Point(22,y);backgrounds.Size=new Size(363,30);backgrounds.SelectedIndexChanged+=(s,e)=>{bgHex.Enabled=backgrounds.SelectedIndex==2;UpdateTheme();};config.Controls.Add(backgrounds);y+=39;bgHex.Location=new Point(22,y);bgHex.Size=new Size(237,27);bgHex.TextChanged+=(s,e)=>UpdateTheme();Button bgPick=Btn("选择背景色",113);bgPick.Location=new Point(272,y-2);bgPick.Click+=(s,e)=>PickColor(true);config.Controls.Add(bgHex);config.Controls.Add(bgPick);y+=39;icons.Text="内置蓝色图标同步换色";icons.Location=new Point(22,y);icons.AutoSize=true;icons.CheckedChanged+=(s,e)=>UpdateTheme();config.Controls.Add(icons);y+=43;
 AddLabel(config,"03  我的主题",12,FontStyle.Bold,y);y+=32;name.Location=new Point(22,y);name.Size=new Size(237,27);name.MaxLength=40;name.TextChanged+=(s,e)=>{if(!loading)theme.Name=name.Text.Trim();};config.Controls.Add(name);Button save=Btn("保存主题",113);save.Location=new Point(272,y-2);save.Click+=(s,e)=>SaveTheme();config.Controls.Add(save);y+=38;saved.DropDownStyle=ComboBoxStyle.DropDownList;saved.Location=new Point(22,y);saved.Size=new Size(237,28);saved.SelectedIndexChanged+=(s,e)=>{if(!loading&&saved.SelectedIndex>=0){try{theme=Storage.Read(themeFiles[saved.SelectedIndex]);LoadFields();}catch(Exception ex){Error(ex.Message);}}};config.Controls.Add(saved);Button import=Btn("导入 / 导出",113);import.Location=new Point(272,y-2);ContextMenuStrip menu=new ContextMenuStrip();menu.Items.Add("导入主题…",null,(s,e)=>Import());menu.Items.Add("导出当前主题…",null,(s,e)=>Export());import.Click+=(s,e)=>menu.Show(import,new Point(0,import.Height));config.Controls.Add(import);
 Panel right=new Panel{Dock=DockStyle.Fill,BackColor=Color.White,Padding=new Padding(22)};body.Controls.Add(right,1,0);TableLayoutPanel rp=new TableLayoutPanel{Dock=DockStyle.Fill,RowCount=4,ColumnCount=1};rp.RowStyles.Add(new RowStyle(SizeType.Absolute,39));rp.RowStyles.Add(new RowStyle(SizeType.Percent,100));rp.RowStyles.Add(new RowStyle(SizeType.Absolute,32));rp.RowStyles.Add(new RowStyle(SizeType.Absolute,68));right.Controls.Add(rp);previewLabel.Text="效果预览";previewLabel.Font=new Font(Font.FontFamily,14,FontStyle.Bold);previewLabel.Dock=DockStyle.Fill;rp.Controls.Add(previewLabel,0,0);rp.Controls.Add(preview,0,1);rp.Controls.Add(new Label{Text="效果示意 · 头像和消息图片不套用整体滤镜",Dock=DockStyle.Fill,ForeColor=Color.FromArgb(129,137,151),TextAlign=ContentAlignment.MiddleLeft},0,2);
 TableLayoutPanel pathRow=new TableLayoutPanel{Dock=DockStyle.Fill,ColumnCount=2,RowCount=2,Margin=new Padding(0)};pathRow.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,100));pathRow.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute,72));pathRow.RowStyles.Add(new RowStyle(SizeType.Absolute,24));pathRow.RowStyles.Add(new RowStyle(SizeType.Absolute,32));pathRow.Controls.Add(new Label{Text="客户端位置",Dock=DockStyle.Fill,ForeColor=Color.FromArgb(129,137,151)},0,0);clientPath.Text="D:\\WXWorkLocal\\westlake\\westlake.exe";clientPath.Dock=DockStyle.Fill;pathRow.Controls.Add(clientPath,0,1);Button browse=Btn("浏览",64);browse.Dock=DockStyle.Fill;browse.Margin=new Padding(7,0,0,0);browse.Click+=(s,e)=>{using(OpenFileDialog f=new OpenFileDialog{Filter="i西湖 客户端|westlake.exe"})if(f.ShowDialog(this)==DialogResult.OK)clientPath.Text=f.FileName;};pathRow.Controls.Add(browse,1,1);rp.Controls.Add(pathRow,0,3);

 TableLayoutPanel footer=new TableLayoutPanel{Dock=DockStyle.Fill,ColumnCount=3,RowCount=1,Padding=new Padding(0,16,0,0)};footer.RowStyles.Add(new RowStyle(SizeType.Percent,100));footer.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,100));footer.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute,122));footer.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute,182));Panel statePanel=new Panel{Dock=DockStyle.Fill,MinimumSize=new Size(200,40)};status.AutoSize=true;status.Location=new Point(0,2);status.Font=new Font(Font.FontFamily,10,FontStyle.Bold);hint.AutoSize=true;hint.Location=new Point(0,27);hint.ForeColor=Color.FromArgb(124,133,148);statePanel.Controls.Add(status);statePanel.Controls.Add(hint);footer.Controls.Add(statePanel,0,0);restore=Btn("恢复默认",114);restore.Dock=DockStyle.Fill;restore.Margin=new Padding(0,0,10,0);restore.Click+=async(s,e)=>await Run(true);footer.Controls.Add(restore,1,0);apply=Btn("应用到 i西湖",180);apply.BackColor=Color.FromArgb(48,52,66);apply.ForeColor=Color.White;apply.Dock=DockStyle.Fill;apply.Click+=async(s,e)=>await Run(false);footer.Controls.Add(apply,2,0);page.Controls.Add(footer,0,2);LoadFields();RefreshSaved();RefreshStatus();timer.Interval=5000;timer.Tick+=(s,e)=>{if(!busy)RefreshStatus();};timer.Start();}
 Button Btn(string text,int width){return new Button{Text=text,Width=width,Height=34,FlatStyle=FlatStyle.Flat,BackColor=Color.FromArgb(247,248,250),ForeColor=Color.FromArgb(55,61,76),Cursor=Cursors.Hand,FlatAppearance={BorderColor=Color.FromArgb(225,228,234)}};}
 void AddLabel(Control parent,string text,int size,FontStyle style,int y){parent.Controls.Add(new Label{Text=text,Location=new Point(22,y),AutoSize=true,Font=new Font(Font.FontFamily,size,style),ForeColor=Color.FromArgb(46,52,66)});}
 void LoadFields(){loading=true;accent.Text=theme.Accent;name.Text=theme.Name;icons.Checked=theme.Icons;backgrounds.SelectedIndex=theme.Background=="default"?0:theme.Background.ToLower()=="#ffffff"?1:2;bgHex.Text=theme.Background=="default"?"#FFFFFF":theme.Background;bgHex.Enabled=backgrounds.SelectedIndex==2;loading=false;UpdateTheme();}
 void UpdateTheme(){if(loading)return;try{Theme.ColorValue(accent.Text.Trim());if(backgrounds.SelectedIndex==2)Theme.ColorValue(bgHex.Text.Trim());theme.Accent=accent.Text.Trim().ToUpper();theme.Background=backgrounds.SelectedIndex==0?"default":backgrounds.SelectedIndex==1?"#FFFFFF":bgHex.Text.Trim().ToUpper();theme.Icons=icons.Checked;accent.BackColor=Color.White;bgHex.BackColor=Color.White;preview.Current=theme.Clone();preview.Invalidate();foreach(var b in swatches){b.Chosen=b.Swatch.ToArgb()==Theme.ColorValue(theme.Accent).ToArgb();b.Invalidate();}}catch{accent.BackColor=Color.FromArgb(255,238,238);}}
 void PickColor(bool bg){using(ColorDialog d=new ColorDialog{FullOpen=true}){try{d.Color=Theme.ColorValue(bg?bgHex.Text:accent.Text);}catch{}if(d.ShowDialog(this)==DialogResult.OK){string hex=ColorTranslator.ToHtml(Color.FromArgb(d.Color.R,d.Color.G,d.Color.B));hex="#"+d.Color.R.ToString("X2")+d.Color.G.ToString("X2")+d.Color.B.ToString("X2");if(bg){backgrounds.SelectedIndex=2;bgHex.Text=hex;}else{accent.Text=hex;name.Text="自定义配色";}}}}
 Theme ReadFields(){Theme.ColorValue(accent.Text.Trim());if(backgrounds.SelectedIndex==2)Theme.ColorValue(bgHex.Text.Trim());UpdateTheme();theme.Name=name.Text.Trim();theme.Validate();return theme.Clone();}
 void Error(string msg){MessageBox.Show(this,msg,"湖畔换肤",MessageBoxButtons.OK,MessageBoxIcon.Information);}
 void SaveTheme(){try{Theme t=ReadFields();string path=Path.Combine(Storage.Root,"themes","theme-"+Guid.NewGuid().ToString("N")+".json");Storage.Write(path,Storage.Json.Serialize(t));RefreshSaved();hint.Text="主题已保存到我的主题";}catch(Exception ex){Error(ex.Message);}}
 void RefreshSaved(){loading=true;saved.Items.Clear();themeFiles.Clear();Directory.CreateDirectory(Path.Combine(Storage.Root,"themes"));foreach(string path in Directory.GetFiles(Path.Combine(Storage.Root,"themes"),"*.json")){if(Path.GetFileName(path)=="last-theme.json")continue;try{Theme t=Storage.Read(path);themeFiles.Add(path);saved.Items.Add(t.Name);}catch{}}loading=false;}
 void Import(){using(OpenFileDialog f=new OpenFileDialog{Filter="LakeSkin 主题|*.json"})if(f.ShowDialog(this)==DialogResult.OK){try{theme=Storage.Read(f.FileName);LoadFields();SaveTheme();}catch(Exception ex){Error(ex.Message);}}}
 void Export(){try{Theme t=ReadFields();using(SaveFileDialog f=new SaveFileDialog{Filter="LakeSkin 主题|*.json",FileName="LakeSkin-theme.json"})if(f.ShowDialog(this)==DialogResult.OK)Storage.Write(f.FileName,Storage.Json.Serialize(t));}catch(Exception ex){Error(ex.Message);}}
 void RefreshStatus(){try{var ps=Process.GetProcessesByName("westlake");status.Text=ps.Length==0?"○  i西湖 未运行":ps.Length==1?"●  i西湖 已运行":"检测到多个客户端";if(hint.Text.Length==0)hint.Text="只在点击应用后改变客户端外观";foreach(var p in ps)p.Dispose();}catch{status.Text="无法读取客户端状态";}}
 async Task Run(bool reset){if(busy)return;Theme t;try{t=ReadFields();}catch(Exception ex){if(!reset){Error(ex.Message);return;}t=new Theme();}string path=clientPath.Text.Trim();if(!reset&&(!File.Exists(path)||Path.GetFileName(path).ToLowerInvariant()!="westlake.exe")){Error("请选择已安装的 westlake.exe。");return;}busy=true;apply.Enabled=restore.Enabled=false;status.Text=reset?"正在恢复默认…":"正在应用配色…";try{int code=await Task.Run(()=>{Process[] ps=Process.GetProcessesByName("westlake");if(ps.Length==0&&reset)return 0;if(ps.Length==0){Process.Start(new ProcessStartInfo(path){WorkingDirectory=Path.GetDirectoryName(path)});for(int i=0;i<30;i++){Thread.Sleep(500);ps=Process.GetProcessesByName("westlake");if(ps.Length==1){try{bool ready=false;foreach(ProcessModule m in ps[0].Modules)if(m.ModuleName.Equals("Qt5Widgets.dll",StringComparison.OrdinalIgnoreCase))ready=true;if(ready)break;}catch{}}foreach(var p in ps)p.Dispose();ps=new Process[0];}}
 if(ps.Length!=1)throw new Exception("未找到唯一的 i西湖 进程，请打开客户端后重试。");int pid=ps[0].Id;ps[0].Dispose();if(!reset)Storage.Prepare(t);var info=new ProcessStartInfo(Path.Combine(Storage.Engine,"theme-helper.exe"),pid+" "+(reset?"restore":"apply")){UseShellExecute=false,CreateNoWindow=true,RedirectStandardOutput=true,RedirectStandardError=true};using(Process p=Process.Start(info)){if(!p.WaitForExit(20000))throw new Exception("应用请求超时；请先退出 i西湖 再重新打开，不要反复点击应用。");string result=p.StandardOutput.ReadToEnd()+p.StandardError.ReadToEnd();Storage.Log((reset?"restore":"apply "+t.Accent)+" result="+p.ExitCode+" "+result.Trim());return p.ExitCode;}});
 if(code!=0)throw new Exception(CodeMessage(code));status.Text=reset?"✓  已请求恢复默认":"✓  已应用 "+t.Name;hint.Text=reset?"换色已关闭；必要时重新打开当前页面":"部分第三方页面和 Logo 可能保持原色";}
 catch(Exception ex){status.Text="未能完成应用";hint.Text="请查看提示后重试";Storage.Log("error "+ex.Message);Error(ex.Message);}finally{busy=false;apply.Enabled=restore.Enabled=true;}}
 public static string CodeMessage(int c){switch(c){case 2:return "没有操作客户端的权限。请让本工具与 i西湖 使用相同权限运行。";case 30:return "客户端 Qt 版本不匹配。目前仅适配 Qt 5.15.18，不会继续加载。";case 32:return "客户端已加载另一份 LakeSkin。请完整退出 i西湖，再使用当前目录的软件。";case 31:return "检测到之前的换肤模块。请完整退出 i西湖，再打开并使用本工具。";case 4:return "客户端还未准备好，请稍等后重试。";case 21:return "图标资源缺失或不匹配。请重新解压完整软件包。";case 22:return "已有应用请求正在执行，请稍后重试。";default:return "换肤未完成，错误码 "+c+"。请查看 data/activity.log。";}}
}
static class Program {
 [STAThread] static int Main(string[] args){bool created;using(Mutex mutex=new Mutex(true,"Local\\LakeSkin-ThemeStudio",out created)){if(!created){MessageBox.Show("湖畔换肤已经打开。","LakeSkin");return 0;}Application.EnableVisualStyles();Application.SetCompatibleTextRenderingDefault(false);try{if(args.Length>0&&args[0]=="--self-test"){Theme t=new Theme();t.Validate();if(!Storage.Qss(t).Contains("#CD4880"))throw new Exception("QSS color");if(Storage.Qss(t).Contains("QWidget {background-color"))throw new Exception("Default background changed");bool rejected=false;try{Theme.ColorValue("red;bad");}catch{rejected=true;}if(!rejected)throw new Exception("Color validation");string json=Storage.Json.Serialize(t);Theme round=Storage.Json.Deserialize<Theme>(json);round.Validate();if(round.Accent!=t.Accent||!round.Icons)throw new Exception("Roundtrip");t.Background="#FFFFFF";if(!Storage.Qss(t).Contains("background-color:#FFFFFF"))throw new Exception("Custom background");File.WriteAllText(Path.Combine(Storage.Root,"self-test.txt"),"PASS: defaults, accent QSS, custom background, invalid color rejection, JSON roundtrip");return 0;}MainWindow f=new MainWindow();if(args.Length==2&&args[0]=="--render"){f.Show();Application.DoEvents();using(Bitmap bmp=new Bitmap(f.Width,f.Height)){f.DrawToBitmap(bmp,new Rectangle(0,0,bmp.Width,bmp.Height));bmp.Save(args[1]);}f.Close();return 0;}Application.Run(f);return 0;}catch(Exception ex){Storage.Log(ex.ToString());MessageBox.Show(ex.Message,"LakeSkin");return 1;}}}
}
}
